### ISSUE TITLE
Refactor Source Code

### ISSUE THREAD

**Issue by BlackCentipede** [BlackCentipede/PearlCLR#2]
Any refactoring/idea/approach are welcomed.

**Comment by rexiaxm7** [comment]
I tried refactoring to improve readability. Please comfirm my PR.

**Comment by guntbert** [comment]
@rexiaxm7 did you forget to actually create a pull request? I cannot see one.

**Comment by BlackCentipede** [comment]
@guntbert It's in #3 I've merged his change for type resolver, that a good idea going forward. The issue is still up since we still gotta think think about how we can break up opcodes into a readable fashion. I will work on it starting Friday to have it broken up into JIT Compiler Context, Opcodes Grouping, and so forth.

**Comment by BlackCentipede** [comment]
Getting more things done with Refactor branch: https://github.com/BlackCentipede/PearlCLR/tree/Refactor

Introduced Opcode Handler Modules, JIT Context, Function Context, and so forth.

**Comment by BlackCentipede** [comment]
> 
> 
> I tried refactoring to improve readability. Please comfirm my PR.

Also is it okay that the changes you made would be licensed under MIT and I've included you in the copyright notice for your contribution?

**Comment by rexiaxm7** [comment]
@BlackCentipede  No problem. Thanks.

**Comment by BlackCentipede** [comment]
I believe I successfully refactored the code into something manageable and it have demonstrated to work. I'll be closing this issue now that it have been resolved.
